### PR TITLE
Add Method getVersion

### PR DESCRIPTION
**Pull request by luqz**
For cita Issues #282

https://github.com/cryptape/cita/issues/282

### CODE REVIEW

**Comment by rainchen** [comment]
No UT or IT test for this change?

**Comment by kaikai1024** [comment]
> No UT or IT test for this change?

No, Just proto files  in this repo.

**Comment by rainchen** [comment]
> > No UT or IT test for this change?
> 
> No, Just proto files in this repo.

OK, I see.

**Comment by kaikai1024** [comment]
@luqz You can @ citaman in the reviewers next time. We'll check it asap.

**Pull request merged**
